version: '3.8'
services:
  bookmarker-ui-nextjs:
    container_name: bookmarker-ui-nextjs
    build:

      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    environment:
      SERVER_SIDE_API_BASE_URL: http://bookmarker-api:8080
      CLIENT_SIDE_API_BASE_URL: http://localhost:18080